package it.getconnected.filippo.me.services;


import android.os.Bundle;

/**
 * Interface that deals with sending events and errors to the Mobile Engagement Service.
 * Both events and errors can happen within a session or not (for example if they are
 * generated by an Android service running in the background), and they can have
 * additional information attached to them in the form of a Bundle.
 * <p>The system also handles events with a duration, which are called jobs. Jobs need
 * to be started and ended explicitly and they can have their own events and errors.</p>
 */
public interface MEEventsSender extends MEServiceModule {

    public void sendEvent(String name, Bundle extras);
    public void sendSessionEvent(String name, Bundle extras);

    public void sendError(String name, Bundle extras);
    public void sendSessionError(String name, Bundle extras);

    public void startJob(String name, Bundle extras);
    public void sendJobEvent(String eventName, String jobName, Bundle extras);
    public void sendJobError(String errorName, String jobName, Bundle extras);
    public void endJob(String name);
}
